role:
  created_date: "20240215"
  name: opendatahub-create-dsc
  description: |
    The Data Science Cluster (DSC) serves as the main object within OpenDataHub, aiding in the configuration of serverless settings dependent on KServe. It enables the installation and uninstallation of each component of RHOAI. While verification is included for kserve/modelmesh/dashboard components, currently other components are not verified.
  manifests:
    datasciencecluster: commons/manifests/opendatahub/datasciencecluster.yaml
  input_env:
    - name: OPENDATAHUB_TYPE
      description: The opendatabub operator type (opendatahub,rhoai)

    - name: DATASCIENCECLUSTER_NAME
      description: The name of dsc object
    
    - name: DEFAULT_DEPLOYMENTMODE
      description: Set default deploymentMode for KServe (Serverless, RawDeployment)
      
    - name: ENABLE_CODEFLARE
      description: Deploy code flare (Removed, Managed)

    - name: ENABLE_DASHBOARD
      description: Deploy dashboard (Removed, Managed)
  
    - name: CUSTOM_DASHBOARD_MANIFESTS 
      description: Set the url, if you want to use custom manifests for DASHBOARD (ex https://github.com/opendatahub-io/odh-dashboard/tarball/f/pipelines-v2)  
    - name: ENABLE_DATASCIENCEPIPELINES
      description: Deploy pipelines (Removed, Managed)

    - name: ENABLE_KSERVE
      description: Deploy Kserve (Managed, Removed)

    - name: CUSTOM_KSERVE_MANIFESTS 
      description: Set the url, if you want to use custom manifests for Kserve (ex https://github.com/jooho/kserve/tarball/global-ca)

    - name: CUSTOM_ODH_MODEL_CONTROLLER_MANIFESTS 
      description: Set the url, if you want to use custom manifests for ODH MODEL CONTROLLER (ex https://github.com/jooho/odh-model-controller/tarball/global-ca)
      
    - name: ENABLE_KSERVE_KNATIVE (Managed, Removed)
      description: Deploy serverless dependencies

    - name: ENABLE_MODELMESH
      description: Deploy modelmesh (Removed, Managed)

    - name: CUSTOM_MODELMESH_MANIFESTS 
      description: Set the url, if you want to use custom manifests for MODELMESH (ex https://github.com/jooho/modelmesh-serving/tarball/global-ca)
 
    - name: ENABLE_RAY
      description: Deploy ray (Removed, Managed)

    - name: ENABLE_TRUSTYAI
      description: Deploy Trust AI (Removed, Managed)

    - name: ENABLE_WORKBENCHES
      description: Deploy workbenches (Removed, Managed)
      
    - name: ENABLE_TRAININGOPERATOR
      description: Deploy training operator (Removed, Managed)

    - name: ENABLE_KUEUE
      description: Deploy kueue (Removed, Managed)

    - name: ENABLE_MODELREGISTRY
      description: Deploy model registry (Removed, Managed)                  

    - name: CLUSTER_TYPE
      description: openshift platform
      required: true

    - name: CLUSTER_API_URL
      description: openshift api url
      required: true      

    - name: CLUSTER_ADMIN_ID
      description: openshift cluster user id
      required: true

    - name: CLUSTER_ADMIN_PW
      description: openshift cluster user password
      required: true

    - name: CLUSTER_TOKEN  
      description: openshift cluster login token
      