playbook:
  name: template
  description: template
  steps:
    - role:
        name: openshift-install
        input_env:
          OSIA_CONFIGURATION_KEY_PATH: "/tmp/"
    - unit:
        name: install-odh-2.5-operator      
    - role:
        name: operator-install
        input_env:
          SUBSCRIPTION_NAME: serverless-operator
          OPERATOR_NAMESPACE: openshift-serverless
          OPERATOR_NAME: serverless-operator
          CATALOGSOURCE_NAME: redhat-operators
