playbook:
  created_date: 20240221
  name: deploy-ssl-minio
  description: Generate certificate and apply it to Minio
  steps:
   - role:
       name: cert-generate
       input_env:
          SAN_LIST: minio.minio.svc.cluster,minio.minio.svc          
   - role:
       name: minio-deploy
       input_env:
         ENABLE_SSL: "true"
    
