# Labels for labeling issues and pull requests using GitHub prow action.
kind:
    - 'bug'
    - 'discussion'
    - 'feature'
    - 'process'
    - 'question'

area:
    - 'roles'
    - 'units'
    - 'playbooks'
    - 'docs'
    - 'examples'
    - 'cli'
    - 'core'
    

priority:
    - 'p0'
    - 'p1'
    - 'p2'