default_vars_file: commons/default-variables.yaml
# enable_print_input_env: false
output_target_dir: ""
output_root_dir: /tmp/ms_cli
output_env_dir: output
output_artifacts_dir: artifacts
output_report_file: report
show_debug_log: false
stop_when_failed: false
stop_when_error_happened: false
enable_loopy_report: true
enable_loopy_logo: true
enable_loopy_log: true
ignore_validate_input_env: true
keep_env_variables:
  - CLUSTER_API_URL
  - CLUSTER_TYPE
  - CLUSTER_ADMIN_ID
  - CLUSTER_ADMIN_PW
  - CLUSTER_TOKEN
  - MINIO_S3_SVC_URL
  - MINIO_DEFAULT_BUCKET_NAME
  - MINIO_ACCESS_KEY_ID
  - MINIO_SECRET_ACCESS_KEY
  - MINIO_REGION
  - JENKINS_USER
  - JENKINS_TOKEN
  - JENKINS_URL
  - CUSTOM_KSERVE_MANIFESTS
  - HF_TEST_TOKEN
additional_role_dirs: [] #example /home/roles
additional_unit_dirs: [./tests/test-data/units]
additional_playbook_dirs: [./tests/test-data/playbooks]

# Logger Configuration
logging:
  version: 1
  disable_existing_loggers: False
  formatters:
    simple:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    detailed:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s - [%(filename)s:%(lineno)d]"
    colored:
      (): colorlog.ColoredFormatter
      format: "%(log_color)s%(asctime)s %(levelname)s:[%(filename)s:%(lineno)3d] %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
      log_colors:
        DEBUG: "cyan"
        INFO: "light_blue"
        WARNING: "yellow"
        ERROR: "red"
        CRITICAL: "bold_red"

  handlers:
    console:
      class: logging.StreamHandler
      level: ERROR
      formatter: colored
      stream: ext://sys.stdout
    file:
      class: logging.FileHandler
      level: DEBUG
      formatter: detailed
      filename: loopy.log
      mode: w

  root:
    level: DEBUG
    handlers: [console, file]
