playbook:
  created_date: "20240320"
  support: "false"
  description: >
    This is a playbook to install kserve serverless mode. It installs required operators(serverless/ossm) then install ODH the latest version operator though fast branch. 
    
    Tested operator version:
    - ODH 2.12.1
    - Authorino 0.11.1
    - Serverless 1.32
    - OSSM 2.5.0
  steps:
   - unit:
       name: install-authorino-stable-operator      
       description: Install Authorino operator stable version    
   - unit:
       name: install-odh-stable-operator    
       description: Install ODH operator fast version  
       input_env:
         CHANNEL: "fast"
   - unit:
       name: install-serverless-stable-operator         
       description: Install Serverless operator stable version  
   - unit:
       name: install-ossm-stable-operator  
       description: Install ServiceMesh operator stable version  
   - role:
       name: opendatahub-create-dsci       
       description: Create a default DSCI.
   - role:
       name: opendatahub-create-dsc
       description: Deploy KServe component.
