playbook:
  created_date: 20240215
  name: deploy-odh-2.5-on-new-cluster
  steps:
   - role:
       name: openshift-install
       input_env:
         OSIA_CONFIGURATION_KEY_PATH: "/tmp/"
   - unit:
       name: install-odh-2.5-operator
    
      