apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sources-pvc
  labels:
    pipeline: caikit-pipeline-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi