role:
  created_date: "20240401"
  name: kserve-inference-test-from-notebook
  description: |
    This role is to deploy a notebook that will in turn deploy a sample model using Kserve and test inference from within the notebook.    
    This role assumes that ODH/RHOAI is installed along with the necessary depencencies. 
    IF using minio, the minio bucket must have a mnist model in the path "kserve-samples/mnist/"
    
    A example of how to run it:
    
     ./loopy roles run kserve-inference-test-from-notebook \
        -p TEST_NAMESPACE=test \ 
        -p MINIO_ACCESS_KEY_ID=your-access-key \ 
        -p MINIO_SECRET_ACCESS_KEY=your-secret-key \ 
        -p CLUSTER_API_URL=https://api.openshiftapps.com:443 \
        -p CLUSTER_ADMIN_ID=user \
        -p CLUSTER_ADMIN_PW=passwd \
  manifests:
    test_notebook: ./manifests/kserve_notebook.ipynb
    service_manifests: ./manifests/service.yaml
    statefulset_manifests: ./manifests/statefulset.yaml
  input_env:
    - name: TEST_NAMESPACE
      required: true
      description: Namespace where test objects will be deployed
    - name: MINIO_ACCESS_KEY_ID
      required: true
      description: Any valid s3 access key 
    - name: MINIO_SECRET_ACCESS_KEY
      description: Any valid s3 access key 
      required: true
    - name: USE_MINIO
      description: set value to "true" if you want to use a minio deployment as the source of the model instead of aws s3
    - name: MINIO_S3_SVC_URL
      description: if using minio, provide minio endpoint
    - name: MODEL_PATH
      description: if using minio, provide model path for onnx model
      
    - name: CLUSTER_API_URL
      description: target cluster to deploy (https://api.example.com:6443), can be obtained through ui or "oc config view --minify -o jsonpath='{.clusters[*].cluster.server}'"
      required: true
    - name: CLUSTER_ADMIN_ID
      description: openshift cluster user id
      required: true
    - name: CLUSTER_ADMIN_PW
      description: openshift cluster user password
      required: true
    - name: CLUSTER_TOKEN  
      description: openshift cluster login token
