playbook:
  created_date: "20240215"
  # name: kserve-serverless-simple-sanity-test-on-existing-cluster
  support: "true"
  description: >
    This is a playbook for kserve end to end test. It installs required operators(serverless/ossm) then install RHOAI the latest version operator though stable branch. After kserve is ready, it will deploy minio pod and deploy caikit-tgis runtime and verify it is working or not.

    (note) at the moment, downloading the runtime take too long so sometimes it returns fail because of long downloading time.
    
    Operator version:
    - RHOAI 2.8.0
    - Authorino 0.10.0
    - Serverless 1.32
    - OSSM 2.5.0
  steps:
   - unit:
       name: install-authorino-stable-operator      
       description: Install Authorino operator stable version    
   - unit:
       name: install-rhoai-stable-operator      
       description: Install RHOAI operator from stable channel
   - unit:
       name: install-serverless-stable-operator   
       description: Install Serverless operator stable version      
   - unit:
       name: install-ossm-stable-operator    
       description: Install ServiceMesh operator stable version            
   - unit:
       name: install-pipelines-stable-operator        
       description: Install Pipeline operator stable version            
   - role:
       name: opendatahub-create-dsc
       input_env:
         OPENDATAHUB_TYPE: rhoai
   - unit:
       name: test-kserve-caikit-tgis-rest       
       description: Trigger sanity test with caikit-tgis-rest    
