unit:
  created_date: "20240410"
  name: test-modelmesh-openvino
  description: |
    This deploy modelmesh openvino runtime with mnist
  steps:
    - role:
        name: minio-deploy  
    - role:
        name: modelmesh-openvino-test
