playbook:
  created_date: 20240215
  name: kserve-sanity-test-on-existing-cluster
  support: "true"
  description: >
    This is a playbook for kserve end to end test. It installs required operators(serverless/ossm) then install RHOAI the latest version operator though stable branch. After kserve is ready, it will deploy minio pod and deploy caikit-tgis runtime and verify it is working or not.

    (note) at the moment, downloading the runtime take too long so sometimes it returns fail because of long downloading time.
  steps:
   - unit:
       name: install-serverless-stable-operator         
   - unit:
       name: install-ossm-stable-operator                
   - unit:
       name: install-rhoai-stable-operator      
   - unit:
       name: deploy-rhoai-kserve
   - role:
       name: minio-deploy
   - unit:
       name: test-kserve-caikit-tgis-rest       
    
