playbook:
  created_date: "20240311"
  support: "false"
  description: Clean up all objects related for kserve/rhoai.
  steps:
    - role:
        name: shell-execute
        input_env:
          COMMANDS: |
            # webhook
            oc delete validatingwebhookconfiguration inferencegraph.serving.kserve.io                        %%
            oc delete validatingwebhookconfiguration inferenceservice.serving.kserve.io                      %%
            oc delete validatingwebhookconfiguration modelmesh-servingruntime.serving.kserve.io              %%
            oc delete validatingwebhookconfiguration servingruntime.serving.kserve.io                        %%
            oc delete validatingwebhookconfiguration trainedmodel.serving.kserve.io                          %%
            oc delete validatingwebhookconfiguration istio-validator-data-science-smcp-istio-system          %%
            oc delete validatingwebhookconfiguration config.webhook.istio.networking.internal.knative.dev    %%
            oc delete validatingwebhookconfiguration openshift-operators.servicemesh-resources.maistra.io    %%
            oc delete validatingwebhookconfiguration config.webhook.istio.networking.internal.knative.dev    %%         
            oc delete validatingwebhookconfiguration config.webhook.serving.knative.dev                      %%         
            oc delete validatingwebhookconfiguration $(oc get validatingwebhookconfiguration|grep validating.knativeeventings.operator.serverless.openshift|awk '{print $1}') %%
            oc delete validatingwebhookconfiguration $(oc get validatingwebhookconfiguration|grep validating.knativekafkas.operator.serverless.openshift.io|awk '{print $1}')  %%
            oc delete validatingwebhookconfiguration $(oc get validatingwebhookconfiguration|grep validating.knativeservings.operator.serverless.openshift|awk '{print $1}')  %%
            oc delete validatingwebhookconfiguration validation.webhook.domainmapping.serving.knative.dev             %% 
            oc delete validatingwebhookconfiguration validation.webhook.serving.knative.dev                          %%

            oc delete mutatingwebhookconfiguration $(oc get mutatingwebhookconfiguration |grep mutating.knativeeventings.operator.serverless.openshift |awk '{print $1}')   %%
            oc delete mutatingwebhookconfiguration $(oc get mutatingwebhookconfiguration |grep mutating.knativeservings.operator.serverless.openshift.io |awk '{print $1}')   %%
            oc delete mutatingwebhookconfiguration webhook.domainmapping.serving.knative.dev                          %%
            oc delete mutatingwebhookconfiguration webhook.istio.networking.internal.knative.dev                      %%
            oc delete mutatingwebhookconfiguration webhook.serving.knative.dev                                        %%
            oc delete mutatingwebhookconfiguration istiod-data-science-smcp-istio-system                              %%
            oc delete mutatingwebhookconfiguration webhook.istio.networking.internal.knative.dev                      %%
            oc delete mutatingwebhookconfiguration  $(oc get mutatingwebhookconfiguration |grep mutating.knativeeventings.operator.serverless.openshift |awk '{print $1}')    %%
            oc delete mutatingwebhookconfiguration  $(oc get mutatingwebhookconfiguration |grep mutating.knativeservings.operator.serverless.openshift.io |awk '{print $1}')    %%
            oc delete mutatingwebhookconfiguration inferenceservice.serving.kserve.io                                 %%

            # Test NS
            oc delete pod,isvc,servingruntime --all --force --grace-period=0 -n kserve-demo                           %%
            oc patch ns kserve-demo -p '{"metadata": {"finalizers": []}}' --type=merge                                %%
            oc delete ns kserve-demo --force --grace-period=0                                                         %%

            oc delete pod,isvc,servingruntime --all --force --grace-period=0 -n pipeline-demo                           %%
            oc patch ns pipeline-demo -p '{"metadata": {"finalizers": []}}' --type=merge                                %%
            oc delete ns pipeline-demo --force --grace-period=0               

            oc delete pod --all --force --grace-period=0                                                              %%
            oc delete ns minio --force --grace-period=0                                                               %%

            # Delete Kserve
            oc patch dsc rhoai -p '{"metadata": {"finalizers": []}}' --type=merge         %%
            oc patch dsci default-dsci -p '{"metadata": {"finalizers": []}}' --type=merge %%
            oc delete dsc --all --force --grace-period=0                                  %%
            oc delete dsci --all --force --grace-period=0                                 %%
            sleep 10                                                                      %%
            oc delete pods -n redhat-ods-applications --all --force --grace-period=0      %%
            oc delete ns redhat-ods-applications --force --grace-period=0                 %%

            # Delete redhat-ods-operator
            oc delete sub,pod --all --force --grace-period=0 -n redhat-ods-operator             %% 
            oc patch ns redhat-ods-operator -p '{"metadata": {"finalizers": []}}' --type=merge  %%
            oc delete ns redhat-ods-operator redhat-ods-monitoring --force --grace-period=0     %%

            # Dependences
            oc delete ServiceMeshControlPlane,pod --all -n istio-system --force --grace-period=0  -n istio-system %%
            oc delete smmr,smm --all --force --grace-period=0  -n istio-system                                    %%

            oc delete KnativeServing,pod --all -n rhoai-serverless --force --grace-period=0  %%
            oc patch ns rhoai-serverless -p '{"metadata": {"finalizers": []}}' --type=merge  %%
            oc patch ns knative-serving -p '{"metadata": {"finalizers": []}}' --type=merge   %%
            oc patch ns knative-eventing -p '{"metadata": {"finalizers": []}}' --type=merge  %%
            oc delete pod,deployment,all --all -n knative-serving  --force --grace-period=0  %%
            oc patch knativeservings.operator.knative.dev knative-serving -n knative-serving -p '{"metadata": {"finalizers": []}}' --type=merge  %% 
            oc delete knativeservings.operator.knative.dev --all -n knative-serving --force --grace-period=0 %%

            oc delete ns rhoai-serverless knative-serving knative-eventing                  %%

            oc patch ns istio-system -p '{"metadata": {"finalizers": []}}' --type=merge     %%
            oc delete ns istio-system                                                       %%

            # OPENDATAHUB
            oc delete sub,pod --all --force --grace-period=0 -n opendatahub                 %%
            oc patch ns opendatahub -p '{"metadata": {"finalizers": []}}' --type=merge      %% 
            oc delete ns opendatahub --force --grace-period=0                               %%

            # openshift-operators
            oc delete sub opendatahub-operator --force --grace-period=0 -n openshift-operators                           %%
            oc delete csv -n openshift-operators $(oc get csv -n openshift-operators |grep opendatahub|awk '{print $1}') %%

            oc delete sub authorino-operator --force --grace-period=0 -n openshift-operators                                    %%
            oc delete csv -n openshift-operators $(oc get csv -n openshift-operators |grep authorino-operator|awk '{print $1}') %%

            oc delete sub servicemeshoperator --force --grace-period=0 -n openshift-operators                                     %%
            oc delete csv $(oc get csv -n openshift-operators | grep servicemeshoperator|awk '{print $1}') -n openshift-operators %%

            oc delete sub serverless-operator --force --grace-period=0 -n openshift-operators                                      %%
            oc delete csv $(oc get csv -n openshift-operators | grep serverless-operator|awk '{print $1}') -n openshift-serverless %%

            oc delete sub openshift-pipelines-operator-rh  --force --grace-period=0 -n openshift-operators %%
            oc delete csv $(oc get csv -n openshift-operators | grep openshift-pipelines-operator-rh |awk '{print $1}') -n openshift-operators %%

            oc delete csv OperatorGroup serverless-operators -n openshift-serverless                                               %%
            # InstallPlan
            for installplan in $(oc get installPlan -n openshift-operators|egrep 'authorino|serverless|servicemeshoperator|pipeline'|awk '{print $1}'); do        oc delete installPlan -n openshift-operators $installplan; done 
