playbook:
  created_date: "20240320"
  description: |
    This playbook will deploy kserve rawDeployment mode with rhoai.

    It installs required operators(authorino) and install RHOAI operator through stable branch. 

    Tested operator version:
    - RHOAI 2.8.0
    - Authorino 0.10.0
  steps:
    - unit:
       name: install-rhoai-stable-operator-without-dsci
       description: Install RHOAI operator from stable channel
    - role:
        name: opendatahub-create-dsci 
        description: Create a DSCI set servicemesh to "Removed"
        input_env:
            OPENDATAHUB_TYPE: rhoai
            ENABLE_SERVICEMESH: Removed
    - role:
        name: opendatahub-create-dsc
        description: Create a DSC setting knative to "Removed" and defaultDeploymentMode to "RawDeployment"
        input_env:
            OPENDATAHUB_TYPE: rhoai
            ENABLE_KSERVE: Managed
            ENABLE_KSERVE_KNATIVE: Removed         
            DEFAULT_DEPLOYMENTMODE: RawDeployment
  
