playbook:
  created_date: "20240320"
  name: install-kserve-serverless-on-existing-cluster
  support: "true"
  description: >
    This is a playbook to install kserve serverless mode. It installs required operators(serverless/ossm) then install RHOAI the latest version operator though stable branch. 
    
    Operator version:
    - RHOAI 2.8.0
    - Authorino 0.10.0
    - Serverless 1.32
    - OSSM 2.5.0
  steps:
   - unit:
       name: install-authorino-stable-operator          
       input_env:
         OPERATOR_VERSION: "v0.10.0"
         INSTALL_APPROVAL: Manual
   - unit:
       name: install-rhoai-stable-operator      
       input_env:
         OPERATOR_VERSION: "2.8.0"
         INSTALL_APPROVAL: Manual
   - unit:
       name: install-serverless-stable-operator         
       input_env:
         OPERATOR_VERSION: "v1.32.0"
         INSTALL_APPROVAL: Manual
   - unit:
       name: install-ossm-stable-operator    
       input_env:
         OPERATOR_VERSION: "v2.5.0"
         INSTALL_APPROVAL: Manual              
   - unit:
       name: deploy-rhoai-kserve
