apiVersion: dscinitialization.opendatahub.io/v1
kind: DSCInitialization
metadata:
  name: %dsci_name%
  labels:
    app.kubernetes.io/created-by: %application_namespace%-operator
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dscinitialization
    app.kubernetes.io/part-of: %application_namespace%-operator
spec:
  applicationsNamespace:  %application_namespace%
  monitoring:
    namespace:  %monitoring_namespace%
    managementState: %enable_monitoring%
  serviceMesh:
    auth:
      audiences:
        - 'https://kubernetes.default.svc'
    controlPlane:
      metricsCollection: Istio
      name: data-science-smcp
      namespace: %istio_namespace%
    managementState: %enable_servicemesh%
  trustedCABundle:
    managementState: %enable_trustedCABundle%
    customCABundle: ""