role:
  created_date: "20240320"
  name: openshift-fips-install
  description: |
    This role install the FIPS Enabled Cluster we do rely on the QE Jenkins rhods-smoke pipeline.        
    The default cluster name is `ods-ci-fips-ms`. This should be possible to retrieve this information by querying the hive.

    This role is to install an openshift cluster. It can be used to install a PSI cluster. It can also be used to 
    install a FIPS enabled cluster. 
    The role will install the cluster and return the console url, api url, admin id and admin password and token.
    
    Input Environment:

    This role takes input parameters to facilitate the installation of an OpenShift cluster on PSI Using QE Pipeline.
    The parameters include:
      - CLUSTER_TYPE: Specifies the type of cluster being installed (e.g., PSI, ROSA).
      - JENKINS_USER: Jenkins username used for authentication.
      - JENKINS_TOKEN: Jenkins token used for authentication.
      - JENKINS_JOB_URL: URL of the Jenkins job associated with the cluster installation.
      - EXTRA_PARAMS: Additional parameters for installing the FIPS-enabled cluster.
      - OSIA_CONFIGURATION_KEY_PATH: Path to the private key for the OSAI repository.
      - CLUSTER_NAME: Name of the OpenShift cluster being installed.
      - MACHINE_POOL_TYPE: Specifies the type of OpenShift node.
    
    
    Output Environment:

    After successful execution, the openshift-install role provides output environment variables containing essential 
    information about the installed OpenShift cluster.
    The output variables include:
      - CLUSTER_CONSOLE_URL: URL of the OpenShift console.
      - CLUSTER_API_URL: URL of the OpenShift API.
      - CLUSTER_TYPE: Type of the OpenShift cluster (PSI, ROSA).
      - CLUSTER_ADMIN_ID: User ID of the OpenShift cluster administrator.
      - CLUSTER_ADMIN_PW: Password of the OpenShift cluster administrator.
      - CLUSTER_TOKEN: Login token for accessing the OpenShift cluster.
    
    To run it:
    ./loopy roles run openshift-install \
      -p CLUSTER_TYPE=FIPS \
      -p JENKINS_USER=username \
      -p JENKINS_TOKEN=jenkins_user_token \
      -p JENKINS_JOB_URL=jenkins_job_url 

    To see the full list of extra parameters:
    ./loopy roles run openshift-install \
      -p CLUSTER_TYPE=FIPS \
      -p JENKINS_USER=username \
      -p JENKINS_TOKEN=jenkins_user_token \
      -p JENKINS_JOB_URL=jenkins_job_url \
      -p EXTRA_PARAMS="-h"

  input_env:
    - name: CLUSTER_TYPE
      description: Type of cluster
      default: PSI

    - name: JENKINS_USER
      description: Jenkins username
      required: true

    - name: JENKINS_TOKEN
      description: Jenkins token
      required: true

    - name: JENKINS_JOB_URL
      description: URL of Jenkins job
      required: true

    - name: EXTRA_PARAMS
      description: Extra parameters for for installing the fips enabled cluster, for all available use -h, e.g. EXTRA_PARAMS="-em email@test.com -n clustername"

  output_env:
    - name: CLUSTER_CONSOLE_URL
      description: openshift console url

    - name: CLUSTER_API_URL
      description: openshift api url

    - name: CLUSTER_TYPE
      description: openshift cluster type (PSI, ROSA)

    - name: CLUSTER_ADMIN_ID
      description: openshift cluster user id

    - name: CLUSTER_ADMIN_PW
      description: openshift cluster user password

    - name: CLUSTER_TOKEN
      description: openshift cluster login token
