playbook:
  created_date: "20240215"
  # name: kserve-serverless-simple-sanity-test-on-existing-cluster
  support: "true"
  description: >
    This is a playbook for kserve end to end test. It installs required operators(serverless/ossm) then install ODH the latest version operator though stable branch. After kserve is ready, it will deploy minio pod and deploy caikit-tgis runtime and verify it is working or not.

    (note) at the moment, downloading the runtime take too long so sometimes it returns fail because of long downloading time.
    
    Tested operator version:
    - ODH 2.9.0
    - Authorino 0.10.0
    - Serverless 1.32
    - OSSM 2.5.0
  steps:
   - unit:
       name: install-authorino-stable-operator          
       description: Install Authorino operator stable version
   - unit:
       name: install-odh-stable-operator      
       description: Install ODH operator fast version
       input_env:
         CHANNEL: "fast"
   - unit:
       name: install-serverless-stable-operator   
       description: Install Serverless operator stable version      
   - unit:
       name: install-ossm-stable-operator    
       description: Install ServiceMesh operator stable version   
   - role:
       name: opendatahub-create-dsci       
       description: Create a default DSCI.       
   - role:
       name: opendatahub-create-dsc
       description: Install KServe component.
   - unit:
       name: test-kserve-caikit-tgis-rest       
       description: Trigger sanity test with caikit-tgis-rest    
