playbook:
  created_date: "20240320"
  # name: install-rhoai-kserve-serverless-on-existing-cluster
  support: "true"
  description: >
    This is a playbook to install kserve serverless mode. It installs required operators(serverless/ossm) then install RHOAI the latest version operator though stable branch. 
    
    Tested operator version:
    - RHOAI 2.8.0
    - Authorino 0.10.0
    - Serverless 1.32
    - OSSM 2.5.0
  steps:
   - unit:
       name: install-rhoai-stable-operator      
   - unit:
       name: install-serverless-stable-operator         
   - unit:
       name: install-ossm-stable-operator    
   - role:
       name: opendatahub-create-dsc
       input_env:
         OPENDATAHUB_TYPE: rhoai
