apiVersion: v1
kind: Secret
metadata:
  annotations:
    serving.kserve.io/s3-endpoint: %minio_s3_svc_url% # replace with your s3 endpoint e.g minio-service.kubeflow:9000
    serving.kserve.io/s3-usehttps: "0" # by default 1, if testing with minio you can set to 0
    serving.kserve.io/s3-region: "%minio_region%"
    serving.kserve.io/s3-useanoncredential: "false" # omitting this is the same as false, if true will ignore provided credential and use anonymous credentials
  name: storage-config
stringData:
  "AWS_ACCESS_KEY_ID": "%minio_access_key_id%"
  "AWS_SECRET_ACCESS_KEY": "%minio_secret_access_key%"
