apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
labels:
  opendatahub.io/dashboard: "true"
metadata:
  annotations:
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    openshift.io/display-name: TGIS Standalone ServingRuntime for KServe
  name: tgis-grpc-runtime
spec:
  containers:
    - args:
        - --model-name=/mnt/models/
        - --port=3000
        - --grpc-port=8033
      command:
        - text-generation-launcher
      env:
        - name: TRANSFORMERS_CACHE
          value: /tmp/transformers_cache
      image: quay.io/opendatahub/text-generation-inference@sha256:e50101c1245b22e080b5754efb7c2b69fd1422e5a608d276eab249bdc5cc5a55
      livenessProbe:
        exec:
          command:
            - curl
            - localhost:3000/health
        initialDelaySeconds: 5
      name: kserve-container
      ports:
        - containerPort: 8033
          name: h2c
          protocol: TCP
      readinessProbe:
        exec:
          command:
            - curl
            - localhost:3000/health
        initialDelaySeconds: 5
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: pytorch
