playbook:
  created_date: "20240221"
  support: "false"
  description: |
    Install dependent operators/Create DSCi with global cert/Generate certificate and apply it to Minio/Deploy KServe model. This playbook will show full steps how to use central ca to pull an model.
    This is tested with ODH 2.9+
  steps:
    - unit:
        name: loopy-roles-test-non-cluster-cert-generate
        description: "playbook-generate certificate"
        input_env:
          SAN_DNS_LIST: minio.minio.svc.cluster,minio.minio.svc
          STOP_WHEN_FAILED: "True"
    # - role:
    #     name: cert-generate
    #     description: "generate certificate"
    #     input_env:
    #       SAN_DNS_LIST: minio.minio.svc.cluster,minio.minio.svc
    #       STOP_WHEN_FAILED: "True"
    - role:
        name: shell-execute
        description: playbook-shell
        input_env:
          COMMANDS: |
            echo "playbook-role-c1" %% echo "playbook-role-c2"          

    # - unit:
    #     name: loopy-test-kubectl         
    #     description: TEST_TEST
      #(example)
      #       oc new-project kserve-demo %% oc label ns/kserve-demo opendatahub.io/dashboard="true"
      #       kubectl patch DSCInitialization default-dsci --type=json -p='[{"op": "add", "path": "/spec/trustedCABundle", "value": {"managementState": "Managed", "customCABundle": ""}}]'  %%  hostname
