apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-storage-config-task
spec:
  params:
    - name: OC_IMAGE
      description: Image to be used for the CaiKit Runtime, defaults to python:3.9.
      type: string
    - name: WORKING_NAMESPACE
      type: string
    - name: MINIO_ACCESS_KEY_ID
      type: string
    - name: MINIO_SECRET_ACCESS_KEY
      type: string
    - name: MINIO_S3_SVC_URL
      type: string
    - name: DEFAULT_BUCKET_NAME
      type: string
    - name: MINIO_REGION
      type: string            
  steps:
    - name: deploy-secret
      image: $(params.OC_IMAGE)
      script: |
        # add the storage-config secret for minio credentials
        oc apply -n $(params.WORKING_NAMESPACE) -f - <<YAML
        apiVersion: v1
        kind: Secret
        metadata:
          name: storage-config
        stringData: 
          aws-connection-minio: |
            {
              "type": "s3",
              "access_key_id": "$(params.MINIO_ACCESS_KEY_ID)",
              "secret_access_key": "$(params.MINIO_SECRET_ACCESS_KEY)",
              "endpoint_url": "$(params.MINIO_S3_SVC_URL)",
              "bucket": "${params.DEFAULT_BUCKET_NAME}",
              "default_bucket": "${params.DEFAULT_BUCKET_NAME}",
              "region": "${params.MINIO_REGION}"
            }
        YAML
      resources: {}
