apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-isvc-task
spec:
  workspaces:
    - name: source
  results:
    - name: output
      description: Generic output you can use as a result
  params:
    - name: PYTHON_IMAGE
      description: Image to be used for the CaiKit Runtime, defaults to python:3.9.
      type: string
    - name: CLUSTER_API_ENDPOINT
      type: string
    - name: TOKEN
      type: string
    - name: PROTOCOL
      type: string
    - name: ISVC_DEPLOYMENT_VERBOSE
      type: string
    - name: WORKING_NAMESPACE
      type: string
  steps:
    - name: deploy-isvc
      image: $(params.PYTHON_IMAGE)
      script: |
        cd $(workspaces.source.path)/src/roles/kserve/pipeline/scripts
        pip install -r requirements.txt
        echo "executing -> python deploy-isvc.py -p $(params.PROTOCOL) -n $(params.WORKING_NAMESPACE)"
        python deploy-isvc.py -p $(params.PROTOCOL) -n $(params.WORKING_NAMESPACE) -d $(workspaces.source.path)
        
        cat $(workspaces.source.path)/output-envs.properties
      resources: {}