unit:
  created_date: "20241009"  
  description: This unit is to test role "kserve-samples-caikit-runtime".
  steps: 
    - role:
        name: operator-install
        description: Install OpenDataHub operator
        input_env:
          SUBSCRIPTION_NAME: opendatahub-operator
          OPERATOR_NAMESPACE: openshift-operators
          OPERATOR_NAME: opendatahub-operator
          OPERATOR_LABEL: "name=error"
          OPERATOR_POD_PREFIX: "opendatahub"
          CONFIG_ENV: "name=DISABLE_DSC_CONFIG"
    - role:
        name: opendatahub-create-dsci 
        description: Create a DSCI set servicemesh to "Removed"
        input_env:
            ENABLE_SERVICEMESH: Removed
    - role:
        name: opendatahub-create-dsc
        description: Create a DSC setting knative to "Removed" and defaultDeploymentMode to "RawDeployment"
        input_env:
            ENABLE_KSERVE: Managed
            ENABLE_KSERVE_KNATIVE: Removed         
            DEFAULT_DEPLOYMENTMODE: RawDeployment 
    - role:
        name: minio-deploy
        description: Install Minio
    - role:
        name: kserve-caikit-test
        description: "[TEST] RawDeployment mode"
        input_env:
          CAIKIT_ARCH_TYPE: caikit-tgis
          PROTOCOL: rest
          ISVC_STORAGE_PATH_TYPE: storage
          TEST_NAMESPACE: kserve-demo
          STORAGE_CONFIG_TYPE: json
          ISVC_DEPLOYMENT_MODE: RawDeployment
          KEEP_NAMESPACE: "false"
