apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: tgis-grpc-runtime
  annotations:
    openshift.io/display-name: TGIS Standalone ServingRuntime for KServe (gRPC)
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
labels:
  opendatahub.io/dashboard: 'true'
spec:
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: pytorch
  containers:
    - name: kserve-container
      image: text-generation-inference
      command: ["text-generation-launcher"]
      args: 
        - "--model-name=/mnt/models/"
        - "--port=3000"
        - "--grpc-port=8033"
      env:
        - name: TRANSFORMERS_CACHE
          value: /tmp/transformers_cache
      readinessProbe:
        exec:
          command:
            - curl
            - localhost:3000/health
        initialDelaySeconds: 5
      livenessProbe:
        exec:
          command:
            - curl
            - localhost:3000/health
        initialDelaySeconds: 5
      ports:
      - containerPort: 8033
        name: h2c
        protocol: TCP
