unit:
  created_date: "20240320"
  name: install-pipelines-stable-operator
  description: This unit install the latest verion of Openshift Pipelines operator using stable channel. 
  steps:
  - role:
      name: operator-install
      input_env:
        SUBSCRIPTION_NAME: openshift-pipelines-operator-rh
        OPERATOR_NAMESPACE: openshift-operators
        OPERATOR_NAME: openshift-pipelines-operator-rh
        CATALOGSOURCE_NAME: redhat-operators
        OPERATOR_LABEL: "app=openshift-pipelines-operator"
        CHANNEL: latest
