unit:
  created_date: "20240320"
  name: install-pipelines-stable-operator
  description: This unit install the latest verion of Openshift Pipelines operator using stable channel. 
  steps:
  - role:
      name: operator-install
      input_env:
        SUBSCRIPTION_NAME: openshift-pipelines-operator-rh
        OPERATOR_NAMESPACE: openshift-operators
        OPERATOR_NAME: openshift-pipelines-operator-rh
        CATALOGSOURCE_NAME: redhat-operators
        OPERATOR_LABEL: "app=openshift-pipelines-operator"
        CHANNEL: latest
  - role:
        name: shell-execute
        input_env:
          COMMANDS: |
            oc get ns openshift-pipelines  > /dev/null 2>&1 || sleep 120s %%
            oc wait --for=condition=ready  pod -l app.kubernetes.io/part-of=tekton-pipelines -n openshift-pipelines %%
            oc wait --for=condition=ready  pod -l app.kubernetes.io/component=controller -n openshift-pipelines %%
            oc wait crd pipelines.tekton.dev --for=condition=established %%   
            oc wait crd pipelineruns.tekton.dev --for=condition=established %%   
            oc wait crd tasks.tekton.dev --for=condition=established
