unit:
  created_date: "20240215"
  name: example-deploy-rhoai-kserve-with-custom-manifests
  steps:
  - role:
      name: opendatahub-create-dsc
      input_env:
        OPENDATAHUB_TYPE: rhoai
        CUSTOM_KSERVE_MANIFESTS: "kserve"
        CUSTOM_ODH_MODEL_CONTROLLER_MANIFESTS: "odh"
        CUSTOM_MODELMESH_MANIFESTS: "modelmesh"
        CUSTOM_DASHBOARD_MANIFESTS: "dashboard"
    