kind: Secret
apiVersion: v1
metadata:
  name: aws-connection-minio
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/managed: 'true'
  annotations:
    opendatahub.io/connection-type: s3
    openshift.io/display-name: minio
stringData:
  AWS_ACCESS_KEY_ID: %minio_access_key_id%
  AWS_DEFAULT_REGION: %minio_region%
  AWS_S3_BUCKET: %minio_default_bucket_name%
  AWS_S3_ENDPOINT: %minio_s3_svc_url%
  AWS_SECRET_ACCESS_KEY: %minio_secret_access_key%
