playbook:
  created_date: "20240320"
  # name: kserve-raw-simple-sanity-test-on-existing-cluster
  description: |
    This playbook will deploy kserve rawDeployment mode with ODH 2.8.

    This is a playbook for kserve rawDeployment end to end test. It installs ODH operator through fast channel. After kserve is ready, it will deploy minio pod and deploy caikit-tgis runtime and verify it is working or not.

    (note) at the moment, downloading the runtime take too long so sometimes it returns fail because of long downloading time.

    Tested operator version:
    - ODH 2.9.0
  steps:
    - unit:
       name: install-odh-stable-operator-without-dsci
       description: Install ODH operator fast channel
       input_env:
            CHANNEL: "fast"
    - role:
        name: opendatahub-create-dsci 
        description: Create a DSCI set servicemesh to "Removed"
        input_env:
            ENABLE_SERVICEMESH: Removed
    - role:
        name: opendatahub-create-dsc
        description: Create a DSC setting knative to "Removed" and defaultDeploymentMode to "RawDeployment"
        input_env:
            ENABLE_KSERVE: Managed
            ENABLE_KSERVE_KNATIVE: Removed         
            DEFAULT_DEPLOYMENTMODE: RawDeployment 
    - unit:
        name: test-kserve-caikit-tgis-rest
        description: Deploy KServe Caikit Tgis Runtime with RawDeployment Mode. Then check result.
        input_env:
            ISVC_DEPLOYMENT_MODE: RawDeployment
  
