# Add Schema paths
schema:
  role: src/schema/role.yaml
  unit: src/schema/unit.yaml
  playbook: src/schema/playbook.yaml

# Add default components paths
default_roles_dirs:
- src/roles
- ${UNOFFICIAL_COMPONENTS}/roles

default_units_dirs:
- ${UNOFFICIAL_COMPONENTS}/units

default_playbooks_dirs:
- ${UNOFFICIAL_COMPONENTS}/playbooks
