# Add Schema paths
schema:
  role: src/schema/role.yaml
  unit: src/schema/unit.yaml
  playbook: src/schema/playbook.yaml

# Add default components paths
default_roles_dir: src/roles
default_units_dir: ${UNOFFICIAL_COMPONENTS}/units
default_playbooks_dir: ${UNOFFICIAL_COMPONENTS}/playbooks
