apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: %minio_namespace%
spec:
  ports:
    - name: minio-client-port
      port: 9000
      protocol: TCP
      targetPort: 9000
    - name: minio-ui-port
      port: 9001
      protocol: TCP
      targetPort: 9001
  selector:
    app: minio
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: minio
  namespace: %minio_namespace%
spec:
  port:
    targetPort: minio-ui-port
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: minio
    weight: 100
  wildcardPolicy: None
---  
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: minio
  name: minio
  namespace: %minio_namespace%
spec:
  securityContext:
    allowPrivilegeEscalation: false
  containers:
    - args:
        - server
        - /data1
        - --console-address
        - :9001
      env:
        - name: MINIO_ACCESS_KEY
          value: %access_key_id%
        - name: MINIO_SECRET_KEY
          value: %secret_access_key%
      image: %minio_image%
      imagePullPolicy: Always
      name: minio
