apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: %minio_namespace%
spec:
  ports:
    - name: minio-client-port
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: minio
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: minio
  name: minio
  namespace: %minio_namespace%
spec:
  securityContext:
    allowPrivilegeEscalation: false
  containers:
    - args:
        - server
        - /data1
      env:
        - name: MINIO_ACCESS_KEY
          value: %access_key_id%
        - name: MINIO_SECRET_KEY
          value: %secret_access_key%
      image: %minio_image%
      imagePullPolicy: Always
      name: minio
