unit:
  created_date: 20240215
  name: install-serverless-stable-operator
  description: This unit install Serverless operator the latest verion with stable channel. 
  role:
    name: operator-install
    input_env:
      SUBSCRIPTION_NAME: serverless-operator
      OPERATOR_NAMESPACE: rhoai-serverless
      OPERATOR_NAME: serverless-operator
      CATALOGSOURCE_NAME: redhat-operators
      OPERATOR_LABEL: "name=knative-openshift"
