role:
  created_date: "20240215"
  name: operator-install
  description: |
    This role primarily creates a Subscription to install operators using OLM (Operator Lifecycle Manager). If the namespace where the installation occurs is not "openshift-operators," it automatically creates an OperatorGroup before creating the Subscription. Additionally, if the CATALOGSOURCE_IMAGE variable is set, it is determined that a custom CatalogSource is needed, and the role creates the corresponding CatalogSource.
    
    (Example)
    ---
    - unit:
      name: install-rhoai-operator
      input_env:
        CATALOGSOURCE_NAME: rhods-catalog-dev 
        CHANNEL: fast 
        OPERATOR_VERSION: v2.8.0-incubation 
        CATALOGSOURCE_IMAGE: quay.io/opendatahub/opendatahub-operator-catalog:v2.8.0-incubation

    - role:
      name: operator-install
      input_env:
        SUBSCRIPTION_NAME: rhods-operator
        OPERATOR_NAMESPACE: redhat-ods-operator
        OPERATOR_NAME: rhods-operator
        OPERATOR_LABEL: "name=rhods-operator"
        OPERATOR_VERSION: v2.8.0-incubation 
        CHANNEL: fast 
        CATALOGSOURCE_NAME: rhods-catalog-dev 
        CATALOGSOURCE_IMAGE: quay.io/opendatahub/opendatahub-operator-catalog:v2.8.0-incubation
    ---    
  tags:
  - rhoai
  - operator
  manifests:
    subscription: commons/manifests/kubernetes/subscription.yaml
    operatorgroup: commons/manifests/kubernetes/operatorgroup.yaml
    catalogsource: commons/manifests/kubernetes/catalogsource.yaml
  input_env:
    - name: SUBSCRIPTION_NAME
      description: Subscription object name
      required: true

    - name: OPERATOR_NAMESPACE
      description: Namespace where the operator will run      
      required: true

    - name: OPERATOR_LABEL
      description: operator label to verify operator is running well or not
      required: true

    - name: OPERATOR_POD_PREFIX
      description: operator pod prefix to verify operator is running well or not (set this if the operator does not have unique label. It will be used instead of OPERATOR_LABEL)
    
    - name: CHANNEL
      description: Subscription channel
      default: stable
    
    - name: INSTALL_APPROVAL
      description: Upgrade plan approval (Automatic/Manual)

    - name: OPERATOR_NAME
      description: The target operator name to be installed
      required: true

    - name: OPERATOR_VERSION
      description: The target operator version to be installed

    - name: CATALOGSOURCE_NAME
      description: The catalog source name that contains the target operator

    - name: CATALOGSOURCE_NAMESPACE
      description: The namespace that the catalog source is in

    - name: CATALOGSOURCE_IMAGE
      description: The catalogsource image that include the operator you want to install

    - name: OPERATORGROUP_CREATE
      description: Set false, the namespace already have operator group. Automatically it will set to false if OPERATOR_NAMESPACE is `openshift-operators`
      default: "true"

    - name: CONFIG_ENV
      description: Set this, if you want to add config.env.(ex "name=DISABLE_DSC_CONFIG")
      default: ""
      
    - name: CLUSTER_API_URL
      description: openshift api url
      required: true

    - name: CLUSTER_ADMIN_ID
      description: openshift cluster user id
      required: true

    - name: CLUSTER_ADMIN_PW
      description: openshift cluster user password
      required: true

    - name: CLUSTER_TOKEN  
      description: openshift cluster login token
