REPORT_EXECUTION_TIME_ROUND = 3
REPORT_MIN_UNIT = "m"
REPORT_SECOND_UNIT = "s"
REPORT_MAXIMUM_DESCRIPTION_STRING_LENGTH = 70
LOG_STRING_CONFIG = "CONFIG"
DEFAULT_PROVIDED_SERVICES = "unofficial_components"
