unit:
  created_date: 20240221
  name: test-kubectl
  role:
    name: shell-execute
    input_env:
      COMMANDS: |
        kubectl patch DSCInitialization default-dsci --type=json -p='[{"op": "add", "path": "/spec/trustedCABundle", "value": {"managementState": "Managed", "customCABundle": ""}}]'      
