apiVersion: v1
stringData:
  localMinIO: |
    {
      "type": "s3",
      "access_key_id": "%minio_access_key_id%",
      "secret_access_key": "%minio_secret_access_key%",
      "endpoint_url": "%minio_s3_svc_url%",
      "bucket": "%minio_default_bucket_name%",
      "default_bucket": "%minio_default_bucket_name%",
      "region": "%minio_region%"
    }
kind: Secret
metadata:
  name: storage-config
type: Opaque   
