playbook:
  created_date: "20240320"
  description: |
    This playbook will deploy kserve rawDeployment mode with ODH 2.9.

    It installs required operators(authorino 0.10.0) and install RHOAI 2.9.0 version operator though stable branch. 

    operator version:
    - OHD 2.9.0
    - Authorino 0.10.0
  steps:
    - unit:
       name: install-odh-stable-operator-without-dsci
       description: Install ODH operator 2.9.0 version
       input_env:
            OPERATOR_VERSION: "2.9.0"
            INSTALL_APPROVAL: Manual
    - role:
        name: opendatahub-create-dsci 
        description: Create a DSCI set servicemesh to "Removed"
        input_env:
            ENABLE_SERVICEMESH: Removed
    - role:
        name: opendatahub-create-dsc
        description: Create a DSC setting knative to "Removed" and defaultDeploymentMode to "RawDeployment"
        input_env:
            ENABLE_KSERVE: Managed
            ENABLE_KSERVE_KNATIVE: Removed         
            DEFAULT_DEPLOYMENTMODE: RawDeployment
  
