role:
  created_date: "20240322"
  name: openshift-fips-uninstall
  # output_filename: openshift-cluster-output.sh
  description: | 
    Uninstall a cluster from PSI(FIPS) infra.
    
    How to run it:
    ./loopy roles run openshift-fips-uninstall \
      -p JENKINS_USER=user \
      -p JENKINS_TOKEN=jenkins_user_token \
      -p JENKINS_JOB_URL=jenkins_job_url

    The default cluster name is 'serving-ods-ci-fips-ms'
    To override it, use CLUSTER_NAME parameter, e.g. -p CLUSTER_NAME=serving-ods-ci-fips-ms,ods-ci-fips-ms2

  input_env:
    - name: CLUSTER_TYPE
      description: Type of cluster
      default: FIPS

    - name: CLUSTER_NAME
      description: List of clusters to test (optional), comma separated, defaults to serving-ods-ci-fips-ms

    - name: JENKINS_URL
      description: URL of Jenkins Server URL
      required: true

    - name: JENKINS_JOB_URI
      description: URL of Jenkins delete job
      default: job/tools/job/openshift/job/cluster-operations/build

    - name: JENKINS_USER
      description: Jenkins Username
      required: true
    - name: JENKINS_TOKEN
      description: Jenkins Token
      required: true

    - name: EXTRA_PARAMS
      description: Extra parameters for for installing the fips enabled cluster, for all available use -h, e.g. EXTRA_PARAMS="-em email@test.com -n clustername"
