name: Automerge

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: pascalgn/automerge-action@v0.16.4
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          merge-method: squash
          labels: "approved"
          blocking-labels: "hold"
