name: Automerge

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "lgtm,approved,!hold"
          MERGE_METHOD: "squash"
          MERGE_METHOD_LABELS: automerge=merge,autosquash=squash
          MERGE_REQUIRED_STATUSES: "success"
          MERGE_ERROR_FAIL: "true"
          MERGE_WAIT_FOR_STATUSES: "true"
