name: E2E Tests

on:
  pull_request:
    branches: [main]
    paths:
      - "**"
      - "!.github/**"
      - "!.vscode/**"
      - "!docs/**"
      - "!**.md"

env:
  TEST_ENV: ci
  KUBECONFIG: ${{ github.workspace }}/kubeconfig
jobs:
  cluster-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup KIND Cluster
        uses: ./.github/actions/kind-setup

      - name: Verify cluster connection
        run: |
          kubectl cluster-info
          kubectl get nodes
          echo "Current context:"
          kubectl config current-context
        shell: bash

      - name: Run E2E Tests
        shell: bash
        run: |
          make e2e

  non-cluster-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run FVT Tests
        shell: bash
        run: |
          make fvt
