name: Manage ci-passed label

on:
  check_suite:
    types: [completed]
  pull_request:
    types:
      - synchronize

jobs:
  add-label-on-ci-success:
    if: github.event_name == 'check_suite' && github.event.check_suite.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add ci-passed label if all checks passed
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = github.event.check_suite.pull_requests[0];
            if (!pr) {
              console.log("No PR associated");
              return;
            }
            const labels = (await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
            })).data.map(label => label.name);

            if (!labels.includes('ci-passed')) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: ['ci-passed'],
              });
              console.log("Added ci-passed label");
            } else {
              console.log("ci-passed label already exists");
            }

  remove-label-on-new-commit:
    if: github.event_name == 'pull_request' && github.event.action == 'synchronize'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Remove ci-passed label on new commit
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = github.event.pull_request.number;
            const labels = (await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
            })).data.map(label => label.name);

            if (labels.includes('ci-passed')) {
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                name: 'ci-passed',
              });
              console.log("Removed ci-passed label due to new commit");
            } else {
              console.log("ci-passed label not found, nothing to remove");
            }
