# This Github workflow will check every hour for PRs with the lgtm label and will attempt to automatically merge them.
# If the hold label is present, it will block automatic merging.

name: Run Jobs on PR
on: pull_request

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: jpmcb/prow-github-actions@v1
        with:
          jobs: lgtm
          github-token: '${{ secrets.GITHUB_TOKEN }}'