unit:
  created_date: 20240215
  name: install-odh-2.5-operator
  role:
    name: operator-install
    input_env:
      SUBSCRIPTION_NAME: opendatahub-operator
      OPERATOR_NAMESPACE: openshift-operators
      OPERATOR_NAME: opendatahub-operator
      OPERATOR_LABEL: "name=error"
      OPERATOR_POD_PREFIX: "opendatahub"
      OPERATOR_VERSION: "2.5.0"
